import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { Gabarito } from 'next/font/google'; // Importando Gabarito do Google Fonts
import './globals.css';

const gabaritoFont = Gabarito({
  subsets: ['latin'],
  variable: '--font-gabarito',
  display: 'swap',
  // Adicione pesos (weights) específicos se necessário, ex: weight: ['400', '700']
});

// As fontes Geist já exportam suas variáveis CSS diretamente
// const geistSans = GeistSans({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = GeistMono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} ${gabaritoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
